version: '3'

services:
  vueapp:
    container_name: vue-project-client-side
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: purinkk/vue-project-client
    networks:
      - client
    ports:
      - "8080:8080"


networks:
  client:
    name: node-server
    driver: bridge
